
-- 1. TOTAL SALES, PROFIT & ORDERS 
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER,
       SUM(NET_SALES) AS TOTAL_SALES,
       SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM SALES_RECORD;       


-- 2. REGION WISE SALES & PROFIT
SELECT REGION,
      COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER,
      SUM(NET_SALES) AS TOTAL_SALES,
      SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM SALES_RECORD
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;


-- 3. CATEGORY WISE PERFORMANCE
SELECT CATEGORY,
      COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER,
      SUM(NET_SALES) AS TOTAL_SALES,
      SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM SALES_RECORD
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;


-- 4. SUB-CATEGORY WISE PROFITABILITY
SELECT SUB_CATEGORY,
      COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER,
      SUM(NET_SALES) AS TOTAL_SALES,
      SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM SALES_RECORD
GROUP BY SUB_CATEGORY
ORDER BY TOTAL_SALES DESC;


-- 5. TOP 05 PRODUCT BY SALES
SELECT 
    PRODUCT_NAME,
    SUM(NET_SALES) AS TOTAL_SALES
FROM SALES_RECORD
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 5;


-- 6. BOTTOM 05 PRODUCT (LOSS MAKERS)
SELECT 
    PRODUCT_NAME,
    SUM(NET_SALES) AS TOTAL_SALES
FROM SALES_RECORD
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES ASC
LIMIT 5; 


-- 7. DISCOUNT IMPACT ON PROFIT
SELECT 
    ROUND(DISCOUNT,1) AS DISCOUNT_LEVEL,
    SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM SALES_RECORD
GROUP BY DISCOUNT_LEVEL
ORDER BY DISCOUNT_LEVEL;


-- 8. AVERAGE OF PRODUCT
SELECT AVG(PRODUCT_SALES)
FROM (
    SELECT SUM(NET_SALES) AS PRODUCT_SALES
    FROM SALES_RECORD
    GROUP BY PRODUCT_NAME
) AS AVG_TABLE;


-- 9 PRODUCTS ABOVE AVERAGE SALES
SELECT 
    PRODUCT_NAME,
    SUM(NET_SALES) AS TOTAL_SALES
FROM SALES_RECORD
GROUP BY PRODUCT_NAME
HAVING TOTAL_SALES > (
        SELECT AVG(PRODUCT_SALES)
        FROM (
            SELECT SUM(NET_SALES) AS PRODUCT_SALES
            FROM SALES_RECORD
            GROUP BY PRODUCT_NAME
        ) AS AVG_TABLE);


-- 10. LOSS MAKING PRODUCTS BELOW AVERAGE PROFIT
SELECT 
    PRODUCT_NAME,
    SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM SALES_RECORD
GROUP BY PRODUCT_NAME
HAVING TOTAL_PROFIT < (
        SELECT AVG(PRODUCT_PROFIT)
        FROM (
            SELECT SUM(PROFIT_AMOUNT) AS PRODUCT_PROFIT
            FROM SALES_RECORD
            GROUP BY PRODUCT_NAME
        ) AS PROFIT_TABLE);


-- 11. TOP 05 BRANDS BY HIGHEST SALES
SELECT BRAND , SUM(NET_SALES) AS TOTAL_SALES
FROM SALES_RECORD
GROUP BY BRAND 
ORDER BY TOTAL_SALES desc
LIMIT 5;

 
-- 12. TOP 05 CITIES BY HIGEST SALES
SELECT CITY,SUM(NET_SALES) AS TOTAL_SALES
FROM SALES_RECORD
GROUP BY CITY
ORDER BY TOTAL_SALES DESC
LIMIT 3;




















