--  E-COMMERCE SALES ANALYSIS

-- DATABASE
   CREATE DATABASE Flipkart;
   USE FLIPKART;
   
-- SCHMEMA

   CREATE TABLE SALES_RECORD(
ORDER_ID VARCHAR(50) PRIMARY KEY,
ORDER_DATE DATE,
DELIVERY_DATE DATE,
DELIVERY_STATUS VARCHAR(20),
CUSTOMER_ID VARCHAR(20),
CUSTOMER_TYPE VARCHAR(20),
STATE VARCHAR(50),
CITY VARCHAR(50),
REGION VARCHAR(20),
PRODUCT_ID VARCHAR(20),
PRODUCT_NAME VARCHAR(100),
CATEGORY VARCHAR(50),
SUB_CATEGORY VARCHAR(50),
BRAND VARCHAR(50),
QUANTITY INT,
UNIT_PRICE DECIMAL(10,2),
MRP DECIMAL(10,2),
DISCOUNT DECIMAL(5,2),
NET_SALES DECIMAL(10,2),
COST_PRICE DECIMAL(10,2),
PROFIT_AMOUNT DECIMAL(10,2),
PROFIT_MARGIN DECIMAL(5,2),
PAYMENT_MODE VARCHAR(20),
YEAR INT,
MONTH INT,
DELIVERY_DAYS INT,
DELIVERY_PERFORMANCE VARCHAR(20)
);



